# api-gateway/config/config.yaml

# Название и версия сервиса
service_name: "api-gateway"
service_version: "v1.0.0"

# Logging
logging:
  level: "debug"        # info | debug | warn | error
  dev_mode: false     # true — включит удобный вывод для локальной отладки
  format: console     # console | json

# HTTP-сервер
http:
  port: 8080
  read_timeout: "10s"
  write_timeout: "15s"
  idle_timeout: "60s"
  shutdown_timeout: "5s"
  metrics_path: "/metrics"
  healthz_path: "/healthz"
  readyz_path: "/readyz"

# OpenTelemetry
telemetry:
  endpoint: "otel-collector:4317"
  insecure: true
  reconnect_period: "5s"
  timeout: "5s"
  sampler_ratio: 1.0
  service_name:    "api-gateway"
  service_version: "v1.0.0"
