service_name:    "market-data-collector"
service_version: "v1.0.0"

# Binance WebSocket (pkg/binance.Config)
binance:
  ws_url: "wss://stream.binance.com:9443/ws"
  streams:
    - "btcusdt@trade"
    - "ethusdt@trade"
    - "btcusdt@depth"
    - "ethusdt@depth"
  read_timeout:      "30s"
  subscribe_timeout: "5s"
  buffer_size:       20000
  backoff:
    initial_interval: "1s"
    max_interval:     "30s"
    max_elapsed_time: "5m"

# Kafka Producer (KafkaConfig)
kafka:
  brokers:
    - "kafka:9092"
  required_acks:   "all"
  timeout:         "15s"
  compression:     "none"
  flush_frequency: "0s"
  flush_messages:  0
  backoff:
    initial_interval: "1s"
    max_interval:     "30s"
    max_elapsed_time: "5m"
  raw_topic:       "marketdata.raw"
  orderbook_topic: "marketdata.orderbook"

# Logging (logger.Config)
logging:
  level:    "debug"
  dev_mode: true

# HTTP server (httpserver.Config)
http:
  port:              8086
  read_timeout:      "10s"
  write_timeout:     "15s"
  idle_timeout:      "60s"
  shutdown_timeout:  "5s"
  metrics_path:      "/metrics"
  healthz_path:      "/healthz"
  readyz_path:       "/readyz"
