# auth/config/config.yaml

service_name:    "auth"
service_version: "v1.0.0"

# JWT
jwt:
  access_ttl: "15m"
  refresh_ttl: "24h"
  issuer: "auth-service"
  audience: "analytics-system"

# PostgreSQL (TimescaleDB-compatible)
postgres:
  dsn: postgres://user:pass@timescaledb:5432/auth?sslmode=disable
  migrations_dir: "/app/migrations/postgres"

# Logging
logging:
  level:    "debug"
  dev_mode: true
  format:   "console"

# HTTP server for healthz/metrics
http:
  port: 8084
  read_timeout: "10s"
  write_timeout: "15s"
  idle_timeout: "60s"
  shutdown_timeout: "5s"
  metrics_path: "/metrics"
  healthz_path: "/healthz"
  readyz_path: "/readyz"
